hackens_orga/agent/urls.py
"""backend URL Configuration
"""

from rest_framework import routers

from .views import AgentViewSet

router = routers.DefaultRouter()

router.register(r"agent", AgentViewSet)

app_name = "agent-backend"
urlpatterns = router.urls

hackens_orga/budget/urls.py
"""backend URL Configuration
"""

from rest_framework import routers

from .views import BudgetGroupViewSet, BudgetLineViewSet

router = routers.DefaultRouter()

router.register(r"budgetgroup", BudgetGroupViewSet)
router.register(r"budgetline", BudgetLineViewSet)

app_name = "budget-backend"
urlpatterns = router.urls

hackens_orga/frontend/urls.py
from django.urls import include, path

from .views import (BudgetGroupCreateView, BudgetGroupUpdateView,
                    BudgetLineCreateView, BudgetLineUpdateView, BudgetListView)

app_name = "frontend"
urlpatterns = [
    path("", BudgetListView.as_view(), name="budget"),
    path(
        "budget-group/create",
        BudgetGroupCreateView.as_view(),
        name="budget-group-create",
    ),
    path(
        "budget-group/<int:pk>/update",
        BudgetGroupUpdateView.as_view(),
        name="budget-group-update",
    ),
    path(
        "budget-line/create",
        BudgetLineCreateView.as_view(),
        name="budget-line-create",
    ),
    path(
        "budget-line/<int:pk>/update",
        BudgetLineUpdateView.as_view(),
        name="budget-line-update",
    ),
]

hackens_orga/hackens_orga/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("authens/", include("authens.urls")),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("api/budget/", include("budget.urls")),
    path("api/agent/", include("agent.urls")),
    # path("api/wishlist/", include("wishlist.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    path("", include("frontend.urls")),
]

hackens_orga/agent/models.py
from django.contrib.auth.models import User
from django.db import models


class Agent(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    def __repr__(self):
        return f"Agent_{self.name}"

    def __str__(self):
        return self.name

hackens_orga/budget/models.py
from datetime import date

from agent.models import Agent
from django.db import models


class BudgetLine(models.Model):
    amount = models.DecimalField(
        max_digits=12, decimal_places=2, verbose_name="Montant"
    )
    author = models.ForeignKey(Agent, on_delete=models.PROTECT, verbose_name="Auteur")
    comment = models.TextField(blank=True, verbose_name="Commentaire")
    date = models.DateField(default=date.today, verbose_name="Date")
    group = models.ForeignKey(
        "BudgetGroup", on_delete=models.CASCADE, verbose_name="Budget"
    )
    title = models.CharField(max_length=255, verbose_name="Libellé")

    def __str__(self):
        return f"{self.title}"

    def __repr__(self):
        return f"BudgetLine_{self.title}_{self.amount}€"


class BudgetGroup(models.Model):
    name = models.CharField(max_length=255, verbose_name="Intitulé")
    description = models.TextField(blank=True, verbose_name="Description")

    def get_all_lines(self):
        lines = self.budgetline_set.all()
        return lines, sum(i.amount for i in lines)

    def __str__(self):
        return f"{self.name}"

    def __repr__(self):
        return f"BudgetGroup_{self.name}"

hackens_orga/frontend/models.py
from django.db import models

# Create your models here.

hackens_orga/agent/views.py
from rest_framework import viewsets
from rest_framework.permissions import DjangoModelPermissionsOrAnonReadOnly

from .models import Agent
from .serializers import AgentSerializer


class AgentViewSet(viewsets.ModelViewSet):
    queryset = Agent.objects.all()
    serializer_class = AgentSerializer
    permission_class = [DjangoModelPermissionsOrAnonReadOnly]

hackens_orga/budget/views.py
from rest_framework import viewsets
from rest_framework.permissions import DjangoModelPermissionsOrAnonReadOnly

from .models import BudgetGroup, BudgetLine
from .serializers import BudgetGroupSerializer, BudgetLineSerializer


class BudgetGroupViewSet(viewsets.ModelViewSet):
    queryset = BudgetGroup.objects.all()
    serializer_class = BudgetGroupSerializer
    permission_class = [DjangoModelPermissionsOrAnonReadOnly]


class BudgetLineViewSet(viewsets.ModelViewSet):
    queryset = BudgetLine.objects.all()
    serializer_class = BudgetLineSerializer
    permission_class = [DjangoModelPermissionsOrAnonReadOnly]

hackens_orga/frontend/views.py
"""
Frontend views for the app
"""

from agent.models import Agent
from budget.models import BudgetGroup, BudgetLine
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Model
from django.urls import reverse
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  TemplateView, UpdateView)


class BudgetListView(ListView):
    model = BudgetGroup
    template_name = "frontend/budget_list.html"
    ordering = "-name"


class BudgetGroupCreateView(SuccessMessageMixin, PermissionRequiredMixin, CreateView):
    model = BudgetGroup
    fields = ["name", "description"]
    template_name = "frontend/budgetgroup_create.html"
    success_message = "Le budget %(name)s a été créé avec succès"
    permission_required = "budget.add_budgetgroup"

    def get_success_url(self):
        return reverse("frontend:budget")


class BudgetGroupUpdateView(SuccessMessageMixin, PermissionRequiredMixin, UpdateView):
    model = BudgetGroup
    fields = ["name", "description"]
    template_name = "frontend/budgetgroup_create.html"
    success_message = "Le budget %(name)s a été mis à jour avec succès"
    permission_required = "budget.change_budgetgroup"

    def get_success_url(self):
        return reverse("frontend:budget")


class BudgetLineCreateView(SuccessMessageMixin, PermissionRequiredMixin, CreateView):
    model = BudgetLine
    fields = ["title", "comment", "amount", "author", "date", "group"]
    template_name = "frontend/budgetline_create.html"
    success_message = 'La dépense/recette "%(title)s" a été créée avec succès'
    permission_required = "budget.add_budgetline"

    def get_initial(self):
        if "groupid" in self.request.GET:
            try:
                gid = int(self.request.GET["groupid"])
            except ValueError:
                gid = None
            if gid is not None:
                try:
                    grp = BudgetGroup.objects.get(pk=gid)
                except Model.DoesNotExist:
                    grp = None
            else:
                grp = None
            agents = Agent.objects.filter(user=self.user)
            return {"author": agents[0] if len(agents) >= 1 else None, "group": grp}

    def get_success_url(self):
        return reverse("frontend:budget")


class BudgetLineUpdateView(SuccessMessageMixin, UpdateView, PermissionRequiredMixin):
    model = BudgetLine
    fields = ["title", "comment", "amount", "author", "date", "group"]
    template_name = "frontend/budgetline_update.html"
    success_message = 'La dépense/recette "%(title)s" a été mise à jour avec succès'
    permission_required = "budget.change_budgetline"

    def get_success_url(self):
        return reverse("frontend:budget")

hackens_orga/frontend/templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="{% static "css/bundle.css" %}" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static "vendor/fontawesome/css/fontawesome.min.css" %}" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static "vendor/fontawesome/css/solid.min.css" %}" type="text/css" media="screen" charset="utf-8">

    <title>Hackens-orga</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'media/logo.png' %}">
  </head>
  <body class="has-navbar-fixed-top">
    <nav class="navbar is-fixed-top" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://new.hackens.org" >
          <img src="{% static "media/logo.png" %}" alt="Logo d'hackens"/>
        </a>

        <a role="button" class="navbar-burger" data-target="main-menu" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu" id="main-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="{% url "frontend:budget" %}" >
            Budget
          </a>

          <a class="navbar-item" href="https://www.eleves.ens.fr/pads/p/HackensCourses" >
            Liste de courses
          </a>
          {% if user.is_staff %}
          <a class="navbar-item" href="{% url "admin:index" %}" >
            Admin
          </a>
          {% endif %}
        </div>

        <div class="navbar-end">
          {% if user.is_authenticated %}
          <div class="navbar-item">
            <span class="icon-text">
              <span class="icon">
                <i class="fas fa-user"></i>
              </span>
              <span>{{ user.username }}</span>
            </span>
          </div>
          {% endif %}
          <div class="navbar-item">
            <div class="buttons">
              {% if user.is_authenticated %}
              <a class="button is-secondary" href="{% url "authens:logout" %}">
                <strong>Déconnexion</strong>
              </a>
              {% else %}
              <a class="button is-primary" href="{% url "authens:login" %}">
                <strong>Connexion</strong>
              </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="section pt-1 pb-1">
      {% for m in messages %}
      <div class="notification {{ m.level_tag }}" id="message-{{ forloop.counter0 }}">
        <button class="delete" data-target="message-{{ forloop.counter0 }}"></button>
          {{ m }}
        </div>
      {% endfor %}
    </section>
    {% block content %}{% endblock %}
    <script src="{% static "js/bulma-utils.js" %}" defer></script>
  </body>
</html>

hackens_orga/frontend/templates/frontend/budget_list.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}

<section class="section pt-2 content">
  <h1 class="title is-3">Budget d'hackens</h1>
  {% if perms.budget.add_budgetgroup %}
  <div class="buttons">
    <a
      class="button is-dark"
      href="{% url "frontend:budget-group-create" %}"
      >
      <span class="icon">
        <i class="fas fa-plus"></i>
      </span>
      <span>Nouveau budget</span>
    </a>
  </div>
  {% endif %}
  {% for  budgetGroup in object_list %}
  {% with all_lines=budgetGroup.get_all_lines %}
  <div class="level is-mobile">
    <div class="level-left">
      <h2 class="m-0 title is-4 level-item">
        Budget {{ budgetGroup.name }}&nbsp;:&nbsp; <span id="budget-amount-{{ budgetGroup.id }}">{{ all_lines.1 }}</span>€
      </h2>
    </div>
    <div class="level-right">
      <div class="level-item buttons">
        {% if perms.budget.add_budgetline %}
        <a class="button" href="{% url "frontend:budget-line-create" %}" title="Nouvelle ligne de budget">
          <span class="is-hidden-mobile icon-text">
            <span class="icon"><i class="fa-solid fa-circle-plus"></i></span>
            <span>Nouvelle ligne</span>
          </span>
          <span class="is-hidden-tablet icon-text">
            <span class="icon"><i class="fa-solid fa-circle-plus"></i></span>
          </span>
        </a>
        {% endif %}
        {% if perms.budget.change_budgetgroup %}
        <a
          class="button"
          href="{% url "frontend:budget-group-update" budgetGroup.id %}"
          title="Éditer l'intitulé du budget"
          >
            <span class="icon"><i class="fa-regular fa-pen-to-square"></i></span>
        </a>
        {% endif %}
      </div>
    </div>
  </div>
  {% if budgetGroup.description.strip %}
    <p>
      <strong>Description:</strong> {{ budgetGroup.description.strip }}
    </p>
  {% endif %}
  {% for line in all_lines.0|dictsort:"date" %}
    {% if forloop.first %}
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Libellé</th>
          <th>Montant</th>
          <th>Ajouté par</th>
          {% if perms.budget.change_budgetline %}
          <th></th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
    {% endif %}
    <tr id="tableline-{{ line.id }}">
          <td>{{ line.date }}</td>
          <td>{{ line.title }}</td>
          <td>{{ line.amount }}€</td>
          <td>{{ line.author.name }}</td>
          {% if perms.budget.change_budgetline %}
          <td>
            <div class="buttons">
              <a class="button" href="{% url "frontend:budget-line-update" line.id %}">
                <span class="icon"><i class="fa-solid fa-pen-to-square"></i></span>
              </a>
              {% if perms.budget.delete_budgetline %}
              <button data-lineid="{{ line.id }}" data-groupid="{{ budgetGroup.id }}" class="delete-budgetline button">
                <span class="icon"><i class="fa-solid fa-trash"></i></span>
              </button>
              {% endif %}
            </div>
          </td>
          {% endif %}
        </tr>
    {% if forloop.last %}
      </tbody>
    </table>
    {% endif %}
  {% empty %}
  <p class="has-text-centered">Ce budget est vide</p>
  {% endfor %}
  <div class="divider"></div>
  {% endwith %}
  {% endfor %}
</section>

{% if perms.budget.delete_budgetline %}
<script src="{% static "js/budget_list.js" %}" defer></script>
{% endif %}
{% endblock %}

hackens_orga/frontend/templates/frontend/budgetgroup_create.html
{% extends "frontend/base.html" %}
{% block content %}

<section class="section content">
  <h1 class="title is-3">Créer un budget</h1>
  {% include "forms/common-form.html" with c_size="is-12" errors=True %}
</section>

{% endblock %}

hackens_orga/frontend/templates/frontend/budgetgroup_update.html
{% extends "frontend/base.html" %}
{% block content %}

<section class="section content">
  <h1 class="title is-3">Éditer un budget</h1>
  {% include "forms/common-form.html" with c_size="is-12" errors=True %}
</section>

{% endblock %}

hackens_orga/frontend/templates/frontend/budgetline_create.html
{% extends "frontend/base.html" %}
{% block content %}

<section class="section content">
  <h1 class="title is-3">Créer une ligne de budget</h1>
  {% include "forms/common-form.html" with c_size="is-12" errors=True %}
</section>

{% endblock %}

hackens_orga/frontend/templates/frontend/budgetline_update.html
{% extends "frontend/base.html" %}
{% block content %}

<section class="section content">
  <h1 class="title is-3">Éditer le ligne {{ object.title }}</h1>
  {% include "forms/common-form.html" with c_size="is-12" errors=True %}
</section>

{% endblock %}

hackens_orga/shared/templates/forms/checkbox.html
<div class="control">
  {% if field.auto_id %}
  <label class="checkbox {% if field.field.required %}{{ form.required_css_class }}{% endif %}" {% if field.field.disabled %}disabled="" {% endif %}>
    {{ field }} {{ field.label }}
  </label>
  {% endif %}
  {% for error in field.errors %}
  <span class="help is-danger {{ form.error_css_class }}">{{ error }}</span>
  {% endfor %}

  {% if field.help_text %}
  <p class="help">
    {{ field.help_text|safe }}
  </p>
  {% endif %}
</div>

hackens_orga/shared/templates/forms/common-form.html
{% load i18n %}
<form action="" method="post">
  {% csrf_token %}

  {% include "forms/form.html" %}

  <div class="field is-grouped">
    <div class="control is-expanded">
      <button class="button is-fullwidth is-outlined is-primary is-light" type="submit">
        <span class="icon">
          <i class="fas fa-{% if f_icon %}{{ f_icon }}{% else %}check{% endif %}"></i>
        </span>
        <span>{% if f_submit %}{{ f_submit }}{% else %}{% trans "Enregister" %}{% endif %}</span>
      </button>
    </div>
<!--
    <div class="control">
      <a class="button is-primary" href="{{ r_url }}{% if r_anchor %}#{{ r_anchor }}{% endif %}">
        <span class="icon">
          <i class="fas fa-undo-alt"></i>
        </span>
        <span>{% if f_return %}{{ f_return }}{% else %}{% trans "Retour" %}{% endif %}</span>
      </a>
    </div>
-->
  </div>
</form>

hackens_orga/shared/templates/forms/field.html
{% load bulma %}

<div class="field">
  {% if field|is_checkbox %}

  {% include "forms/checkbox.html" %}

  {% elif field|is_radio %}

  {% include "forms/radio.html" %}

  {% elif field|is_input %}

  {% include "forms/input.html" %}

  {% elif field|is_textarea %}

  {% include "forms/textarea.html" %}

  {% elif field|is_select %}

  {% include "forms/select.html" %}

  {% elif field|is_file %}

  {% include "forms/file.html" %}

  {% else %}

  {% include "forms/other.html" %}

  {% endif %}
</div>

hackens_orga/shared/templates/forms/file.html
{% load i18n bulma %}

<label class="label {% if field.field.required %}{{ form.required_css_class }}{% endif %}">
  {{ field.label_tag }}
</label>

<div class="control">

  <div class="file has-name is-fullwidth">
    <label class="file-label">
      {{ field|bulmafy:'file-input' }}
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          {% trans "Choisissez un fichier..." %}
        </span>
      </span>
      <span class="file-name is-expanded has-text-centered">
        {% trans "Aucun fichier sélectionné" %}
      </span>
    </label>
  </div>

  {% for error in field.errors %}
  <span class="help is-danger {{ form.error_css_class }}">{{ error }}</span>
  {% endfor %}

  {% if field.help_text %}
  <p class="help">
    {{ field.help_text|safe }}
  </p>
  {% endif %}
</div>

hackens_orga/shared/templates/forms/form.html
{% if errors %}
{% if form.non_field_errors %}
<div class="notification is-danger px-3 has-text-centered">
  {% for non_field_error in form.non_field_errors %}
  {{ non_field_error }}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
</div>
{% endif %}
{% endif %}

{% for field in form.hidden_fields %}
{{ field }}
{% endfor %}

{% for field in form.visible_fields %}
{% include 'forms/field.html' %}
{% endfor %}

hackens_orga/shared/templates/forms/formset.html
{% if formset.non_form_errors %}
<div class="message is-danger">
  <p class="message-body">
    {% for error in formset.non_form_errors %}
    {{ error }}<br>
    {% endfor %}
  </p>
</div>
{% endif %}

{{ formset.management_form }}
{% for form in formset %}
{% include 'forms/form.html' %}
{% endfor %}

hackens_orga/shared/templates/forms/input.html
{% load bulma %}

<label class="label {% if field.field.required %}{{ form.required_css_class }}{% endif %}">
  {{ field.label_tag }}
</label>

<div class="control">
  {{ field|bulmafy:'input' }}

  {% for error in field.errors %}
  <span class="help is-danger {{ form.error_css_class }}">{{ error }}</span>
  {% endfor %}

  {% if field.help_text %}
  <div class="help">
    {{ field.help_text|safe }}
  </div>
  {% endif %}
</div>

hackens_orga/shared/templates/forms/modal-form.html
{% load i18n %}

<div class="modal" id="modal-{{ modal_id }}">
  <div class="modal-background" data-closes="modal-{{ modal_id }}"></div>
  <div class="modal-card">

    <header class="modal-card-head">
      <p class="modal-card-title">{{ modal_title }}</p>
      <button class="delete" aria-label="close" data-closes="modal-{{ modal_id }}"></button>
    </header>

    <section class="modal-card-body">
      <form method="post" action="{{ post_url }}" id="form-{{ modal_id }}" data-modal="modal-{{ modal_id }}">
        {% csrf_token %}
        {% include "forms/form.html" %}
      </form>
    </section>

    <footer class="modal-card-foot">
      <button class="button is-fullwidth is-outlined is-primary is-light" form="form-{{ modal_id }}" type="submit">
        <span class="icon">
          <i class="fas fa-check"></i>
        </span>
        <span>{% trans "Enregistrer" %}</span>
      </button>

      <button class="button is-primary button-close" data-closes="modal-{{ modal_id }}">
        <span class="icon">
          <i class="fas fa-times"></i>
        </span>
        <span>{% trans "Annuler" %}</span>
      </button>
    </footer>
  </div>
</div>

hackens_orga/shared/templates/forms/other.html
{% if field.auto_id %}
<label class="label {% if field.field.required %}{{ form.required_css_class }}{% endif %}" for="{{ field.auto_id }}">
  {{ field.label }}
</label>
{% endif %}

<div class="control {% if field|is_multiple_checkbox %}multiple-checkbox{% endif %}">
  {{ field }}

  {% for error in field.errors %}
  <span class="help is-danger {{ form.error_css_class }}">{{ error }}</span>
  {% endfor %}

  {% if field.help_text %}
  <p class="help">
    {{ field.help_text|safe }}
  </p>
  {% endif %}
</div>

hackens_orga/shared/templates/forms/radio.html
{% if field.auto_id %}
<label class="label {% if field.field.required %}{{ form.required_css_class }}{% endif %}">
  {{ field.label_tag }}
</label>
{% endif %}

<div class="control">
  {% for choice in field %}
  <label class="radio">
    {{ choice.tag }}
    {{ choice.choice_label }}
  </label>
  {% endfor %}

  {% for error in field.errors %}
  <span class="help is-danger {{ form.error_css_class }}">{{ error }}</span>
  {% endfor %}

  {% if field.help_text %}
  <p class="help">
    {{ field.help_text|safe }}
  </p>
  {% endif %}
</div>

hackens_orga/shared/templates/forms/select.html
{% load bulma %}

<label class="label {% if field.field.required %}{{ form.required_css_class }}{% endif %}">
  {{ field.label_tag }}
</label>

<div class="control is-expanded">
  <span class="select is-fullwidth{% if field|is_multiple_select %} is-multiple{% endif %}{% if field.errors|length > 0 %} is-danger{% endif %}">
    {{ field }}
  </span>

  {% for error in field.errors %}
  <span class="help is-danger {{ form.error_css_class }}">{{ error }}</span>
  {% endfor %}

  {% if field.help_text %}
  <p class="help">
    {{ field.help_text|safe }}
  </p>
  {% endif %}
</div>

hackens_orga/shared/templates/forms/textarea.html
{% load bulma %}

<label class="label {% if field.field.required %}{{ form.required_css_class }}{% endif %}">
  {{ field.label_tag }}
</label>

<div class="control">
  {{ field|bulmafy:'textarea' }}

  {% for error in field.errors %}
  <span class="help is-danger {{ form.error_css_class }}">{{ error }}</span>
  {% endfor %}

  {% if field.help_text %}
  <p class="help">
    {{ field.help_text|safe }}
  </p>
  {% endif %}
</div>